# Generated by Django 5.1.2 on 2024-10-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nome', models.TextField(db_column='nome', max_length=70)),
                ('idade', models.IntegerField(db_column='idade')),
            ],
        ),
    ]
